name: Build and Push The Image

on:
  push:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for multi-platform support, optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}               # Using GitHub Actions runner's default GitHub actor
          password: ${{ secrets.GITHUB_TOKEN }}       # GitHub token for authentication

      # Step 4: Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/trivy-exporter:${{ github.sha }} .
          docker tag ghcr.io/${{ github.repository }}/trivy-exporter:${{ github.sha }} ghcr.io/${{ github.repository }}/trivy-exporter:latest

      # Step 5: Push the Docker image to the registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/trivy-exporter:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/trivy-exporter:latest
